<?php

return [
    \VCD2\Applications\Application::class => \VCD2\Applications\Repository\ApplicationRepository::class,
    \VCD2\Applications\Child::class => \VCD2\Applications\Repository\ChildRepository::class,
    \VCD2\Applications\StepChoice::class => \VCD2\Applications\Repository\StepChoiceRepository::class,
    \VCD2\Applications\Invoice::class => \VCD2\Applications\Repository\InvoiceRepository::class,
    \VCD2\Applications\InvoiceItem::class => \VCD2\Applications\Repository\InvoiceItemRepository::class,
    \VCD2\Applications\ApplicationAddon::class => \VCD2\Applications\Repository\ApplicationAddonRepository::class,
    \VCD2\Credits\CreditMovement::class => \VCD2\Credits\Repository\CreditMovementRepository::class,
    \VCD2\Credits\Credit::class => \VCD2\Credits\Repository\CreditRepository::class,
    \VCD2\Discounts\DiscountCode::class => \VCD2\Discounts\Repository\DiscountCodeRepository::class,
    \VCD2\Discounts\Discount::class => \VCD2\Discounts\Repository\DiscountRepository::class,
    \VCD2\Events\ApplicationStep::class => \VCD2\Events\Repository\ApplicationStepRepository::class,
    \VCD2\Events\ApplicationStepOption::class => \VCD2\Events\Repository\ApplicationStepOptionRepository::class,
    \VCD2\Events\Event::class => \VCD2\Events\Repository\EventRepository::class,
    \VCD2\Events\EventAddon::class => \VCD2\Events\Repository\EventAddonRepository::class,
    \VCD2\Events\EventImage::class => \VCD2\Events\Repository\EventImageRepository::class,
    \VCD2\Users\Child::class => \VCD2\Users\Repository\ChildRepository::class,
    \VCD2\Users\User::class => \VCD2\Users\Repository\UserRepository::class,
    \VCD2\Users\UserRole::class => \VCD2\Users\Repository\UserRoleRepository::class,
    \VCD2\Users\UserSession::class => \VCD2\Users\Repository\UserSessionRepository::class,
    \VCD2\Emails\Email::class => \VCD2\Emails\Repository\EmailRepository::class,
    \VCD2\Emails\Attachment::class => \VCD2\Emails\Repository\AttachmentRepository::class,
    \VCD2\Events\EventTab::class => \VCD2\Events\Repository\EventTabRepository::class,
    \VCD2\Applications\Payment::class => \VCD2\Applications\Repository\PaymentRepository::class,
    \Hafo\GoPay\Payment::class => \Hafo\GoPay\Repository\PaymentRepository::class,
    \VCD2\Applications\PaymentMethod::class => \VCD2\Applications\Repository\PaymentMethodRepository::class,
    \Hafo\Fio\Payment::class => \Hafo\Fio\Repository\PaymentRepository::class,
    \VCD2\Ebooks\Ebook::class => \VCD2\Ebooks\Repository\EbookRepository::class,
    \VCD2\Ebooks\EbookDownload::class => \VCD2\Ebooks\Repository\EbookDownloadRepository::class,
    \VCD2\Ebooks\EbookDownloadLink::class => \VCD2\Ebooks\Repository\EbookDownloadLinkRepository::class,
    \VCD2\Carousel\Carousel::class => \VCD2\Carousel\Repository\CarouselRepository::class,
    \VCD2\Carousel\AbstractCarouselPage::class => \VCD2\Carousel\Repository\CarouselPageRepository::class,
    \VCD2\Carousel\CarouselPage::class => \VCD2\Carousel\Repository\CarouselPageRepository::class,
    \VCD2\Carousel\CarouselEventPage::class => \VCD2\Carousel\Repository\CarouselPageRepository::class,
    \VCD2\Gallery\AbstractPhoto::class => \VCD2\Gallery\Repository\PhotoRepository::class,
    \VCD2\Gallery\Photo::class => \VCD2\Gallery\Repository\PhotoRepository::class,
    \VCD2\Gallery\LostFound::class => \VCD2\Gallery\Repository\PhotoRepository::class,
    \VCD2\Users\Consent::class => \VCD2\Users\Repository\ConsentRepository::class,
    \VCD2\PostOffice\Letter::class => \VCD2\PostOffice\Repository\LetterRepository::class,
    \VCD2\Reviews\Review::class => \VCD2\Reviews\Repository\ReviewRepository::class,
    \VCD2\FacebookImages\FacebookImage::class => \VCD2\FacebookImages\Repository\FacebookImageRepository::class,
    \VCD2\Firebase\FirebasePushToken::class => \VCD2\Firebase\Repository\FirebasePushTokenRepository::class,
];
